language: go

sudo: false

go:
  - 1.5.3
  - 1.6

services:
  - redis-server

install:
  - go get .
  - go get -u github.com/golang/lint/golint

script:
  - set -e
  - go vet .
  - golint .
  - go test -v -tags "redis"


