language: go

sudo: false

go:
  - 1.7
  - 1.8

branches:
  only:
    - master
    - v1

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.ccm/repository
    - $HOME/.local/lib/python2.7

matrix:
  - fast_finish: true

env:
  matrix:
    - DB=memory
    - DB=redis
    - DB=cassandra:2.1.17
    - DB=cassandra:2.2.9
    - DB=cassandra:3.0.12
    - DB=cassandra:3.10

services:
  - redis-server

install:
  - pip install --user cql PyYAML six
  - git clone https://github.com/pcmanus/ccm.git
  - pushd ccm
  - ./setup.py install --user
  - popd
  - go get .
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/stvp/tempredis

script:
  - set -e
  - go vet .
  - golint .
  - JAVA_HOME="/usr/lib/jvm/java-8-oracle" PATH="/usr/lib/jvm/java-8-oracle/jre/bin/:$PATH:$HOME/.local/bin" bash integration.sh "$DB"

notifications:
  - email: false
